#!/bin/bash

# Document Tests - Report Generation, DOCX Creation, PDF Conversion
# Tests Execify as a platform for document generation and conversion

BASE_URL="http://localhost:3000"
API_KEY="test-key-123"

PASS=0
FAIL=0

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
MAGENTA='\033[0;35m'
NC='\033[0m'

test_document() {
  local name="$1"
  local code="$2"
  local language="$3"
  
  echo -e "\n${MAGENTA}[DOCUMENT]${NC} $name"
  
  # Escape code for JSON
  code=$(echo "$code" | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
  
  response=$(curl -s -X POST \
    -H "X-API-Key: $API_KEY" \
    -H "Content-Type: application/json" \
    -d "{\"type\": \"execute\", \"language\": \"$language\", \"code\": \"$code\"}" \
    "$BASE_URL/run")
  
  if echo "$response" | grep -q '"exitCode":0'; then
    echo -e "${GREEN}✓ PASS${NC}"
    ((PASS++))
  else
    echo -e "${RED}✗ FAIL${NC}"
    echo "Response: $response" | head -c 200
    ((FAIL++))
  fi
}

echo -e "\n${MAGENTA}================================================${NC}"
echo -e "${MAGENTA} DOCUMENT TESTS - GENERATION & CONVERSION${NC}"
echo -e "${MAGENTA}================================================${NC}"

# === TEXT REPORTS ===
echo -e "\n${YELLOW}--- Text Reports ---${NC}"

test_document "Generate: Text Report" 'report = """
=== MONTHLY REPORT ===
Date: 2026-04-05

Summary:
- Total Requests: 1,250
- Success Rate: 99.8%
- Avg Response Time: 145ms

Actions:
1. Review performance metrics
2. Optimize database queries
3. Plan infrastructure upgrade
"""
with open("/workspace/report.txt", "w") as f:
    f.write(report)
print("Report generated successfully")' "python"

test_document "Generate: Structured Report" 'import json
report = {
    "date": "2026-04-05",
    "title": "Execify Performance Report",
    "metrics": {
        "requests": 1250,
        "success_rate": 99.8,
        "avg_response_time_ms": 145
    },
    "status": "PASS"
}
with open("/workspace/report.json", "w") as f:
    json.dump(report, f, indent=2)
print("JSON report generated")' "python"

# === CSV EXPORTS ===
echo -e "\n${YELLOW}--- CSV Exports ---${NC}"

test_document "Generate: CSV Data" 'import csv
data = [
    ["ID", "Name", "Email", "Status"],
    [1, "Alice", "alice@example.com", "Active"],
    [2, "Bob", "bob@example.com", "Active"],
    [3, "Charlie", "charlie@example.com", "Inactive"]
]
with open("/workspace/users.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(data)
print("CSV generated with", len(data)-1, "records")' "python"

test_document "Generate: Sales Report CSV" 'import csv
sales = [
    ["Month", "Revenue", "Units", "Growth%"],
    ["Jan 2026", 50000, 250, 10],
    ["Feb 2026", 55000, 275, 15],
    ["Mar 2026", 62000, 310, 20],
    ["Apr 2026", 71000, 355, 25]
]
with open("/workspace/sales.csv", "w", newline="") as f:
    csv.writer(f).writerows(sales)
print("Sales report written")' "python"

# === MARKDOWN DOCUMENTATION ===
echo -e "\n${YELLOW}--- Markdown Documentation ---${NC}"

test_document "Generate: Markdown Documentation" 'markdown = """# Project Documentation

## Overview
Execify is a sandboxed code execution engine.

## Features
- Python execution
- Node.js execution
- File I/O
- Document generation

## Installation
```bash
npm install
docker build -t execify-sandbox ./docker
npm start
```

## API Endpoints
| Endpoint | Method | Auth |
|----------|--------|------|
| /health | GET | No |
| /run | POST | Yes |
| /capabilities | GET | Yes |

## Examples
See docs/examples/ for more.
"""
with open("/workspace/README.md", "w") as f:
    f.write(markdown)
print("Markdown documentation created")' "python"

# === PYTHON DOCX GENERATION ===
echo -e "\n${YELLOW}--- DOCX Generation (python-docx) ---${NC}"

test_document "Generate: DOCX Document" 'from docx import Document
from docx.shared import Pt, Inches

doc = Document()
doc.add_heading("Execify Progress Report", 0)
doc.add_heading("Executive Summary", level=1)
doc.add_paragraph("This is a test document generated by Execify.")

doc.add_heading("Key Metrics", level=1)
table = doc.add_table(rows=4, cols=2)
table.style = "Light Grid Accent 1"
hdr_cells = table.rows[0].cells
hdr_cells[0].text = "Metric"
hdr_cells[1].text = "Value"

rows = [
    ("API Requests", "15,234"),
    ("Success Rate", "99.2%"),
    ("Avg Response", "142ms")
]
for metric, value in rows:
    row_cells = table.add_row().cells
    row_cells[0].text = metric
    row_cells[1].text = value

doc.add_paragraph("Generated by Execify Code Execution Engine")
doc.save("/workspace/report.docx")
print("DOCX document generated successfully")' "python"

# === JSON STRUCTURED DATA ===
echo -e "\n${YELLOW}--- JSON Data Export ---${NC}"

test_document "Generate: Complex JSON Structure" 'import json
from datetime import datetime

data = {
    "timestamp": datetime.now().isoformat(),
    "application": "Execify",
    "version": "1.0.0",
    "endpoints": {
        "health": {"method": "GET", "auth": False},
        "run": {"method": "POST", "auth": True},
        "capabilities": {"method": "GET", "auth": True}
    },
    "languages": ["python", "node"],
    "limits": {
        "timeout_seconds": 25,
        "memory_mb": 512,
        "max_file_size_mb": 10
    },
    "security": {
        "readonly": True,
        "network_isolated": True,
        "api_key_required": True
    }
}

with open("/workspace/metrics.json", "w") as f:
    json.dump(data, f, indent=2)
print("Complex JSON structure written")' "python"

# === MULTI-FILE GENERATION ===
echo -e "\n${YELLOW}--- Multi-File Generation ---${NC}"

test_document "Generate: Multiple Files" 'import json
import csv

# File 1: Config JSON
config = {"app": "Execify", "debug": True}
with open("/workspace/config.json", "w") as f:
    json.dump(config, f)

# File 2: CSV Data
with open("/workspace/data.csv", "w") as f:
    csv.writer(f).writerows([["id", "name"], [1, "test"]])

# File 3: Text Log
with open("/workspace/app.log", "w") as f:
    f.write("[2026-04-05] App started\\n")
    f.write("[2026-04-05] All systems operational\\n")

print("✓ config.json")
print("✓ data.csv")
print("✓ app.log")
print("3 files generated")' "python"

# === NODE.JS JSON GENERATION ===
echo -e "\n${YELLOW}--- Node.js Document Generation ---${NC}"

test_document "Generate: Node-based JSON Report" 'const fs = require("fs");
const report = {
    timestamp: new Date().toISOString(),
    environment: "production",
    services: {
        api: { status: "healthy", uptime: "30 days" },
        database: { status: "healthy", connections: 42 },
        cache: { status: "healthy", hit_rate: 0.95 }
    },
    resources: {
        cpu_usage: 45.2,
        memory_usage: 62.1,
        disk_usage: 78.9
    }
};
fs.writeFileSync("/workspace/system_report.json", JSON.stringify(report, null, 2));
console.log("Node.js report generated: system_report.json");' "node"

# === FILE COMPRESSION ===
echo -e "\n${YELLOW}--- ZIP Archive Generation ---${NC}"

test_document "Generate: ZIP Archive" 'import subprocess
import os

files_to_zip = [
    "/workspace/report.txt",
    "/workspace/report.json",
    "/workspace/users.csv"
]

# Create zip only if files exist
existing = [f for f in files_to_zip if os.path.exists(f)]
if existing:
    subprocess.run([
        "zip", "-j", 
        "/workspace/documents.zip"
    ] + existing, check=True)
    print("Archive created: documents.zip")
else:
    print("No files to archive yet")' "python"

# === SUMMARY ===
echo -e "\n${MAGENTA}================================================${NC}"
TOTAL=$((PASS + FAIL))
PASS_PCT=$((PASS * 100 / TOTAL))
echo -e "Total: $TOTAL | ${GREEN}Pass: $PASS${NC} | ${RED}Fail: $FAIL${NC}"
echo -e "Success Rate: ${GREEN}${PASS_PCT}%${NC}"
echo -e "${MAGENTA}================================================${NC}"

if [ $FAIL -eq 0 ]; then
  echo -e "\n${GREEN}📄 All document tests passed!${NC}"
  echo -e "${GREEN}Execify is ready for document generation.${NC}"
fi

exit $FAIL
